version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"

workflows:
  example:
    jobs:
      - build
      - deploy:
          requires:
            - build
